import { defineConfig } from 'vitepress';

export default defineConfig({
  title: 'ApoRaviz Workspace Docs',
  description: 'Thai-first, topic-organized learning hub for ApoRaviz Angular, Node.js, backend, and tooling.',
  base: '/ApoRaviz_Workspace_Docs/',
  cleanUrls: true,
  rewrites: {
    'AGENTS.md': 'agents.md',
    'CLAUDE.md': 'claude-guide.md',
    'README.md': 'readme.md',
    'PROJECT_START_HERE.md': 'project-start-here.md',
    'WORKSPACE_PLAN.md': 'workspace-plan.md',
    'NEW_PROJECT_GUIDE.md': 'new-project-guide.md',
    'WORKSPACE_RULES.md': 'workspace-rules.md',
    'TEACHING_RULES.md': 'teaching-rules.md',
    'AI_UPDATE_RULE.md': 'ai-update-rule.md',
  },
  lastUpdated: true,
  // ไม่ render bootstrap template files เป็นหน้าเว็บ (มี [[placeholder]]) แต่เก็บ index.md ไว้อธิบายวิธีใช้
  srcExclude: ['templates/project-bootstrap/*.template.md'],
  themeConfig: {
    logo: '/aporaviz-docs-logo.svg',
    nav: [
      { text: 'Start', link: '/project-start-here' },
      { text: 'VitePress', link: '/vitepress/' },
      { text: 'Angular', link: '/angular/' },
      { text: 'Backend', link: '/backend/' },
      { text: 'Labs', link: '/angular/labs/' },
      { text: 'Commands', link: '/commands' },
      { text: 'Claude', link: '/claude/' },
      { text: 'Rules', link: '/workspace-rules' },
    ],
    sidebar: [
      {
        text: 'Start Here',
        items: [
          { text: 'Home', link: '/' },
          { text: 'README', link: '/readme' },
          { text: 'Project Start Here', link: '/project-start-here' },
          { text: 'Workspace Baseline', link: '/baseline' },
          { text: 'Workspace Plan', link: '/workspace-plan' },
          { text: 'New Project Guide', link: '/new-project-guide' },
        ],
      },
      {
        text: 'Workspace Rules',
        collapsed: false,
        items: [
          { text: 'Workspace Rules', link: '/workspace-rules' },
          { text: 'Teaching Rules', link: '/teaching-rules' },
          { text: 'AI Update Rule', link: '/ai-update-rule' },
        ],
      },
      {
        text: 'Claude Code',
        collapsed: false,
        items: [
          { text: 'คำสั่งและความสามารถ', link: '/claude/' },
        ],
      },
      {
        text: 'Angular Learning',
        collapsed: false,
        items: [
          { text: 'Angular Hub', link: '/angular/' },
          {
            text: 'Concepts',
            collapsed: false,
            items: [
              { text: 'Concept Index', link: '/angular/concepts/' },
              { text: 'TypeScript', link: '/angular/concepts/typescript' },
              { text: 'Environment Files', link: '/angular/concepts/environment-files' },
              { text: 'Signal', link: '/angular/concepts/signal' },
              { text: 'Computed', link: '/angular/concepts/computed' },
              { text: 'input() And output()', link: '/angular/concepts/input-output' },
              { text: 'inject()', link: '/angular/concepts/inject' },
              { text: 'SSR Browser Guard', link: '/angular/concepts/ssr-browser-guard' },
              { text: 'Hydration', link: '/angular/concepts/hydration' },
              { text: 'ViewEncapsulation', link: '/angular/concepts/view-encapsulation' },
            ],
          },
          {
            text: 'Labs',
            collapsed: false,
            items: [
              { text: 'Lab Index', link: '/angular/labs/' },
              { text: '01 Signal Counter', link: '/angular/labs/01-signal-counter' },
              { text: '02 Computed Total Price', link: '/angular/labs/02-computed-total-price' },
              { text: '03 Basic Form Input', link: '/angular/labs/03-basic-form-input' },
            ],
          },
          {
            text: 'Core Lessons',
            collapsed: true,
            items: [
              { text: 'Lesson Index', link: '/angular/teach/' },
              { text: '1 Angular 22 Baseline', link: '/angular/teach/angular-22-baseline' },
              { text: '2 TypeScript In Angular', link: '/angular/teach/typescript-in-angular' },
              { text: '3 Angular Run Flow And angular.json', link: '/angular/teach/angular-run-flow-and-angular-json' },
              { text: '4 Angular Config Files', link: '/angular/teach/angular-config-files' },
              { text: '5 Component Structure And Data Flow', link: '/angular/teach/component-structure-data-flow' },
              { text: '6 Reactive State And Signals', link: '/angular/teach/reactive-signals' },
              { text: '7 Services And DI', link: '/angular/teach/services-dependency-injection' },
              { text: '8 App Config, SSR And Hydration', link: '/angular/teach/app-config-ssr-hydration' },
              { text: '9 Browser APIs And SSR Safety', link: '/angular/teach/browser-apis-ssr-safety' },
              { text: '10 Tailwind CSS v4', link: '/angular/teach/tailwind-css-v4' },
              { text: '11 Unit Test And Regression Safety', link: '/angular/teach/unit-test-regression' },
              { text: '12 CI/CD And GitHub Pages', link: '/angular/teach/cicd-github-pages' },
            ],
          },
          {
            text: 'Reference',
            collapsed: true,
            items: [
              { text: 'Tailwind CSS', link: '/angular/tailwind/' },
              { text: 'Angular Commands', link: '/angular/commands' },
            ],
          },
        ],
      },
      {
        text: 'Backend Learning',
        collapsed: false,
        items: [
          { text: 'Backend Stack', link: '/backend/' },
          { text: 'Backend Concepts', link: '/backend/concepts/' },
          { text: 'API Contract', link: '/backend/concepts/api-contract' },
          { text: 'Privilege Escalation', link: '/backend/concepts/privilege-escalation' },
          { text: 'Node.js Hub', link: '/nodejs/' },
          { text: 'Node.js Commands', link: '/nodejs/commands' },
          { text: 'Node.js Concepts', link: '/nodejs/concepts/' },
          { text: 'Environment Variable', link: '/nodejs/concepts/environment-variable' },
          { text: '.env File', link: '/nodejs/concepts/dotenv-file' },
          { text: 'Secret', link: '/nodejs/concepts/secret' },
          { text: '01 Node.js CLI File Processing', link: '/nodejs/teach/01-cli-file-processing' },
          { text: '02 Node Stream And Backpressure', link: '/nodejs/teach/02-node-stream-backpressure' },
          { text: '03 CLI Arguments And Errors', link: '/nodejs/teach/03-cli-arguments-and-errors' },
          { text: '04 File Backup Safety', link: '/nodejs/teach/04-file-backup-safety' },
          { text: '05 Node Test And Temp Files', link: '/nodejs/teach/05-node-test-temp-files' },
          { text: '06 Node And npm Version Check', link: '/nodejs/teach/06-node-npm-version-check' },
          { text: 'NestJS Hub', link: '/nestjs/' },
          { text: 'LINE OA Webhook', link: '/backend/line-oa-webhook' },
          { text: 'Fastify', link: '/backend/fastify' },
          { text: 'PostgreSQL Hub', link: '/postgresql/' },
        ],
      },
      {
        text: 'Commands',
        collapsed: false,
        items: [
          { text: 'Commands Hub', link: '/commands' },
          { text: 'Angular 22 Commands', link: '/angular/commands' },
          { text: 'Node.js Commands', link: '/nodejs/commands' },
          { text: 'Git Commands', link: '/git/commands' },
          { text: 'VitePress Commands', link: '/vitepress/commands' },
        ],
      },
      {
        text: 'Git Learning',
        collapsed: true,
        items: [
          { text: 'Git Commands', link: '/git/commands' },
          { text: 'Git Concepts', link: '/git/concepts/' },
          { text: 'Git Repository', link: '/git/concepts/git-repository' },
          { text: '.gitignore', link: '/git/concepts/gitignore' },
          { text: 'Working Tree', link: '/git/concepts/working-tree' },
          { text: 'Staging Area', link: '/git/concepts/staging-area' },
          { text: 'Commit', link: '/git/concepts/commit' },
          { text: 'HEAD', link: '/git/concepts/head' },
          { text: 'Branch', link: '/git/concepts/branch' },
          { text: 'Merge', link: '/git/concepts/merge' },
          { text: 'Merge Conflict', link: '/git/concepts/merge-conflict' },
          { text: 'Undo In Git', link: '/git/concepts/undo-in-git' },
          { text: 'Reflog', link: '/git/concepts/reflog' },
          { text: 'Stash', link: '/git/concepts/stash' },
          { text: 'Cherry-pick', link: '/git/concepts/cherry-pick' },
          { text: 'Commit Message Convention', link: '/git/concepts/commit-message-convention' },
          { text: 'Remote', link: '/git/concepts/remote' },
        ],
      },
    ],
    socialLinks: [
      { icon: 'github', link: 'https://github.com/ApoRaviz/ApoRaviz_Workspace_Docs' },
    ],
    search: {
      provider: 'local',
    },
    editLink: {
      pattern: 'https://github.com/ApoRaviz/ApoRaviz_Workspace_Docs/edit/main/:path',
      text: 'Edit this page on GitHub',
    },
    lastUpdated: {
      text: 'Last updated',
    },
    outline: {
      label: 'On this page',
      level: [2, 3],
    },
    docFooter: {
      prev: 'Previous',
      next: 'Next',
    },
    darkModeSwitchLabel: 'Theme',
    sidebarMenuLabel: 'Menu',
    returnToTopLabel: 'Return to top',
    langMenuLabel: 'Change language',
  },
});
